# Generated by Django 3.1 on 2020-08-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.IntegerField()),
                ('countryCurrency', models.CharField(max_length=200)),
                ('cities', models.CharField(max_length=200)),
                ('geo_id', models.CharField(max_length=200)),
                ('countryName', models.CharField(max_length=200)),
            ],
        ),
    ]
