# Generated by Django 3.1 on 2020-08-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrate', '0002_geoclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoclass',
            name='countryCode',
            field=models.CharField(max_length=200),
        ),
    ]
